# Generated by Django 3.0.4 on 2020-04-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200324_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.IntegerField(default=2, verbose_name='Creador'),
            preserve_default=False,
        ),
    ]
